version: '3.8'

services:
  mkdocs:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MKDOCS_DEV_ADDR=0.0.0.0:8000
    command: mkdocs serve --dev-addr 0.0.0.0:8000