site_name: Serverchi.uz
site_url: https://serverchi.hihi.uz
site_description: Docker, PostgreSQL va Linux bo'yicha to'plam qo'llanmalar
site_author: Sizning Ismingiz

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: teal

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Bosh sahifa: index.md
  - Docker: docker/index.md
  - PostgreSQL: postgresql/index.md
  - Linux: linux/index.md
  - Qo'llanmalar: tutorials/index.md